### PR TITLE
fix wrong transformer graph generated in some configurations

### PR DESCRIPTION
**Pull request by doudou**
The current code takes zero step to avoid splitting the transform
graph into separate trees. It leads to completely wrong
visualizations quite easily.

This tries very hard to avoid that situation, but still has some
corner cases (e.g. if a transform links the leafs of two transform
trees).

### CODE REVIEW

**Comment by doudou** [comment]
Now you do ;-) Updated with unit tests

**Comment by doudou** [comment]
There are problems left when:
 - the tree becomes a graph. This is definitely possible in a long-running vizkit3d instance where the user modifies its transformation definitions (i.e. transformer design phase)
 - A link joins leaves in two disjoint trees

There would be two simple solutions possible:
 - clear the graph
 - do nothing (and warn the user)

And one that involves reshaping the graph

**Comment by doudou** [comment]
@D-alex: ping

**Comment by D-Alex** [comment]
:+1:

**Pull request merged**
