### PR TITLE
vizkit bugfixes

### PR DESCRIPTION
**Pull request by arneboe**
This PR fixes two bugs:

* In the TransformerGraph a call to `dirtyDisplayList()` was missing.
* In the Vitkit3DWidget `loadPlugin()` used a wrong method to get the absolut path in certain cases.

### CODE REVIEW

**Comment by arneboe** [comment]
@saarnold Kannst du das mergen, bitte? :-)

**Comment by arneboe** [comment]
@jmachowinski Kannst du das mergen, bitte? :)

**Comment by D-Alex** [comment]
Could you test if setUseDisplayList(false) also solves your problem. Calling dirtyDisplayList with high frequency has a significant performance impact.

**Comment by doudou** [comment]
> setUseDisplayList(false)

Moreover, using display list on modern hardware is a huge performance hog, it disables usage of all *BOs.

**Pull request closed without merging**
