### PR TITLE
remove the ancient ruby adapter implementation

### PR DESCRIPTION
**Pull request by doudou**
This has been undocumented and deprecated for years now

It is marked as do-not-merge as I did not build the whole Rock setup with it, so it might break compilation
of some old vizkit3d plugins.

### CODE REVIEW

**Comment by goldhoorn** [comment]
Can you please merge against master, i can to the testing

**Comment by doudou** [comment]
I never pushed it forward because I found out that some vizkit3d plugins still use the API (!). Won't have time for that one in the near future.

**Comment by goldhoorn** [comment]
Can this then be closed to have not depricated PRs layiing around?

**Comment by doudou** [comment]
I would rather keep it here. It's not deprecated, it's an important change and someone has to push it further ... or let it rot here.

**Comment by jmachowinski** [comment]
This should be removed before the next release

**Pull request closed without merging**
