### PR TITLE
add the concept of an environment plugin

### PR DESCRIPTION
**Pull request by doudou**
Environment plugins are plugins that render special environmental
effects that should be applied to the whole scene such as e.g. fog or
water

The upcoming osgOcean plugin would use this feature.

### CODE REVIEW

**Comment by D-Alex** [comment]
Do you think it is enough to support only one environment plugin. In principle they could be chained up.

**Comment by doudou** [comment]
Rebased, and added the call to clearEnvironmentPlugin

**Comment by doudou** [comment]
> Do you think it is enough to support only one environment plugin. In principle they could be chained up.

I think it is "good enough" for now. The best way to allow chaining-up would be to allow chaining vizkit plugins, and that is a very worthwhile change, but I don't have the time to make right now.

**Comment by doudou** [comment]
@D-Alex: Ping ?

**Comment by doudou** [comment]
Ping ping

**Comment by D-Alex** [comment]
I am a bit short on time right now (papers,papers,papers). But I will review the code over Easter (sorry)

**Comment by D-Alex** [comment]
Other than that looks good

**Comment by doudou** [comment]
updated to rename the enable/disable methods and expose them as property

**Comment by D-Alex** [comment]
:+1:

**Pull request merged**
