### PR TITLE
add GL debugging capabilities

### PR DESCRIPTION
**Pull request by doudou**
GL debugging information is dumped to osg::Notify if the VIZKIT_GL_DEBUG
environment variable is set to 1 at startup. The OSG notification level is updated
as well (to DEBUG) to make sure the output actually shows up

### CODE REVIEW

**Comment by jmachowinski** [comment]
Dosen't osg::State::setCheckForGLErrors() do the same thing ?

**Comment by doudou** [comment]
Nope. setCheckForGlErrors seem to control when OSG calls glError (i.e. checks for errors in the various gl* calls). This sets the GL debug backchannel, i.e. diagnostics from the driver.

**Comment by jmachowinski** [comment]
Hm.. I'm not sure if instrumenting the code is the right thing to do.
I recently used opengl debuggers, they give you way more information. 
Have a look at vogl (https://github.com/ValveSoftware/vogl).

**Comment by doudou** [comment]
I know vogl, I've been using it extensively lately. I also have been using glDebug extensively lately. They're been really complementary.

KHD_debug and friends are very low cost, something vogl is very far from being. Moreover, it does not change your code's behaviour (vogl is far from complete and does if you use things it cannot handle -- something osg does a lot), and provides hints for performance improvements (vogl does not, as these are messages usually driver specific).

I know vogl, I've traced osgocean with it. It required something north of 10GB and takes one or two seconds *per frame* (and that's on a quad-core i7, 16GB ram and a discrete nvidia card). Great when you have very nonobvious problems, not so great when you just want low-cost monitoring for your application.

**Comment by jmachowinski** [comment]
Hm, weired, I used vogl lately to optimize Mars. I did not have any performance 
problems with it. Also it created no problems with osg for me. I just tested the
memory foodprint, it is minimal on my machine...

I found it very useful, as you can directly see, what Item is drawn and thus have a
direct knowledge of what causes the problem. 

Anyway, as the code does not have any impact on the runtime if the debug var is not set,
it is ok with me. I just wonder who is Andreas Klein, and why does he have the copyright
on the code ?

**Comment by doudou** [comment]
Because I copy/pasted it from some code of his.

**Comment by doudou** [comment]
> I found it very useful, as you can directly see, what Item is drawn and thus have a
direct knowledge of what causes the problem. 

I completely agree w.r.t. the usefulness of vogl. It is just not a silver bullet ... as these kind of things never are.

**Comment by jmachowinski** [comment]
I'm confused with the LICENCE file. Rock code should be under LGPL v3 not "AS-IS"

**Comment by doudou** [comment]
?? 

Quoting the file:  "vizkit3d is licensed under LGPLv2 or later"

which is the only thing that was ever discussed with Frank

**Comment by jmachowinski** [comment]
The license is a weired mix. Parts of the text are from the MIT license. 
It should look like this : (note this is version 2.1)

Copyright (C) year  name of author

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

**Comment by doudou** [comment]
Would you have missed the header

== Copyright and license for src/EnableGLDebugOperation.hpp and src/EnableGLDebugOperation.cpp

Anyways, I've pushed a modified file, hopes this one makes it clearer.

**Pull request merged**
